// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCiRqwfwD4tHpfIFwbpGCX8mzSWhzErozs',
    appId: '1:1013209014989:web:fa5e6e4d0157b058063f84',
    messagingSenderId: '1013209014989',
    projectId: 'lab4-flutter-1c747',
    authDomain: 'lab4-flutter-1c747.firebaseapp.com',
    storageBucket: 'lab4-flutter-1c747.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD89QFUaOoAey6BbVimcw-T6k8PujgCq58',
    appId: '1:1013209014989:android:7aec73e317228a5a063f84',
    messagingSenderId: '1013209014989',
    projectId: 'lab4-flutter-1c747',
    storageBucket: 'lab4-flutter-1c747.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZEqJNbKqnGWyJc3szwQ6-gy41pgfEPvM',
    appId: '1:1013209014989:ios:d2d0a08b26919bb8063f84',
    messagingSenderId: '1013209014989',
    projectId: 'lab4-flutter-1c747',
    storageBucket: 'lab4-flutter-1c747.firebasestorage.app',
    iosClientId: '1013209014989-gp1potv5jikgpl682tq55pguaq7kr1do.apps.googleusercontent.com',
    iosBundleId: 'com.example.phanphuochongphuc2224802010871Lab4',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZEqJNbKqnGWyJc3szwQ6-gy41pgfEPvM',
    appId: '1:1013209014989:ios:d2d0a08b26919bb8063f84',
    messagingSenderId: '1013209014989',
    projectId: 'lab4-flutter-1c747',
    storageBucket: 'lab4-flutter-1c747.firebasestorage.app',
    iosClientId: '1013209014989-gp1potv5jikgpl682tq55pguaq7kr1do.apps.googleusercontent.com',
    iosBundleId: 'com.example.phanphuochongphuc2224802010871Lab4',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCiRqwfwD4tHpfIFwbpGCX8mzSWhzErozs',
    appId: '1:1013209014989:web:cadffbcb50ea6a23063f84',
    messagingSenderId: '1013209014989',
    projectId: 'lab4-flutter-1c747',
    authDomain: 'lab4-flutter-1c747.firebaseapp.com',
    storageBucket: 'lab4-flutter-1c747.firebasestorage.app',
  );
}
